### ISSUE TITLE
Properly exclude org.slf4j:slf4j-simple dependency from marathon-client.

### ISSUE THREAD

**Issue by thilagasanthosh** [d2iq-archive/marathon-client#15]
The dependency org.slf4j:slf4j-simple:1.7.12:test is downloaded with marathon-client.

But our project uses  "org.slf4j:slf4j-api:jar:1.7.25:compile" and we need to explicitly declare this. So slf4j-simple causing issue with multiple slf4j bindings.

We need to exclude slf4j-simple dependency with marathon-client. So that we no need to add exclusion from our side.

https://github.com/Autoscaler/autoscaler/pull/40/files#diff-902ffa8d7dfbac74e4fd6007ba6b1e94

**Comment by kensipe** [comment]
@thilagasanthosh 👀

**Comment by kensipe** [comment]
on it's way:  https://github.com/mesosphere/marathon-client/pull/16
